### ISSUE TITLE
v2 Performance

### ISSUE THREAD

**Issue by sungo** [joyent/conch#138]
A place to discuss any performance concerns and possible solutions

**Comment by sungo** [comment]
Do we have any active concerns or can we close out this issue?

**Comment by bdha** [comment]
Anecdotally, Mojo feels slightly slower than Dancer did (taking several seconds to load resources instead of immediately.) I don't have any metrics yet, but I do believe this is an actual problem.

**Comment by sungo** [comment]
@bdha In the UI or the API or both?

**Comment by lseppala** [comment]
Knowing which particular resources or UI pages are taking several seconds would be helpful to know for investigation.

**Comment by lseppala** [comment]
@daleghent and @bdha mentioned that the status page was significantly slower to load for the GLOBAL workspace. It seems there's at least two requests loaded on the page which contribute to the slowness, GET `/workspace/:id/device` and `/workspace/:id/relay`.

Below are response times for the Mojo and Dancer app.

Mojo
```
❯ wrk -H 'Cookie: conch=REDACTED' --duration 60 --latency -T 20 https://conch.joyent.us/workspace/496f76b4-8245-4d41-8d97-42fe988401c5/device
Running 1m test @ https://conch.joyent.us/workspace/496f76b4-8245-4d41-8d97-42fe988401c5/device
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     4.75s   478.13ms   6.18s    71.67%
    Req/Sec     2.07      3.21    19.00     88.39%
  Latency Distribution
     50%    4.70s
     75%    5.05s
     90%    5.36s
     99%    6.17s
  120 requests in 1.00m, 149.29MB read
Requests/sec:      2.00
Transfer/sec:      2.48MB
```

Dancer2
```
❯ wrk -H 'Cookie: dancer.session=REDACTED' --duration 60 --latency -T 20 https://preflight.scloud.zone/workspace/496f76b4-8245-4d41-8d97-42fe988401c5/device
Running 1m test @ https://preflight.scloud.zone/workspace/496f76b4-8245-4d41-8d97-42fe988401c5/device
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.22s   369.11ms   3.37s    73.43%
    Req/Sec     5.58      4.51    29.00     81.15%
  Latency Distribution
     50%    1.19s
     75%    1.43s
     90%    1.64s
     99%    2.48s
  489 requests in 1.00m, 628.26MB read
Requests/sec:      8.14
Transfer/sec:     10.46MB
```

The JSON responses are basically identical. A couple device table fields have been added or removed, timestamps are formatted slightly differently. They include the same number of devices.

Both are using the *exact* same SQL query against the same database instance.


It should be noted that for smaller responses, Mojo is faster. Compare the response for `GET /workspace/:id`:

```
❯ wrk -H 'Cookie: conch=REDACTED' --duration 60 --latency -T 20 https://conch.joyent.us/workspace/496f76b4-8245-4d41-8d97-42fe988401c5
Running 1m test @ https://conch.joyent.us/workspace/496f76b4-8245-4d41-8d97-42fe988401c5
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    50.08ms    3.52ms 149.97ms   92.25%
    Req/Sec    98.51     10.25   128.00     78.72%
  Latency Distribution
     50%   49.64ms
     75%   50.49ms
     90%   51.83ms
     99%   60.38ms
  11767 requests in 1.00m, 6.22MB read
Requests/sec:    195.83
Transfer/sec:    105.94KB

❯ wrk -H 'Cookie: dancer.session=REDACTED' --duration 60 --latency -T 20 https://preflight.scloud.zone/workspace/496f76b4-8245-4d41-8d97-42fe988401c5
Running 1m test @ https://preflight.scloud.zone/workspace/496f76b4-8245-4d41-8d97-42fe988401c5
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    53.87ms   26.31ms 679.37ms   99.50%
    Req/Sec    93.88      9.27   118.00     84.64%
  Latency Distribution
     50%   51.58ms
     75%   52.32ms
     90%   54.81ms
     99%   67.05ms
  11231 requests in 1.00m, 4.53MB read
Requests/sec:    186.89
Transfer/sec:     77.19KB
```

There's no clear indication of what is causing the slow-down. Below are some variables I've brainstormed, which may or may not have an impact:

* Mojo and Dancer use different JSON serializers, `Mojo::JSON` and `JSON::XS`, respectively. `JSON::XS` does not build on SmartOS on last test.
* The Dancer2 instance runs on a `g4-general-32G` instance. Mojo runs on a `g4-highcpu-8G` instance` fronted by a nginx proxy running on a `g4-highcpu-4G`
* The object marshaling path between Mojo and Dancer are different.
* There could be a performance difference between Mojo::PG and DBIC for large query results.
* Mojo itself.

Really, I'm guessing. I'll add some timing to see if I can narrow down possible factors.

**Comment by sungo** [comment]
To copy over what I was saying from chat, Mojo uses JSON::PP which itself notes that JSON::XS is much faster. I recommend we test using JSON::MaybeXS and thus CPanel::JSON::XS to see if it makes a difference.

**Comment by lseppala** [comment]
With Mojo::JSON
```
❯ wrk -H 'Cookie: REDACTED --duration 60 --latency -T 20 https://conch.joyent.us/workspace/496f76b4-8245-4d41-8d97-42fe988401c5/device
Running 1m test @ https://conch.joyent.us/workspace/496f76b4-8245-4d41-8d97-42fe988401c5/device
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     4.76s   639.50ms   6.65s    74.17%
    Req/Sec     2.13      2.93    10.00     89.47%
  Latency Distribution
     50%    4.57s
     75%    5.05s
     90%    5.72s
     99%    6.51s
  120 requests in 1.00m, 148.35MB read
Requests/sec:      2.00
Transfer/sec:      2.47MB
```

With Cpanel::JSON::XS loaded via [Mojo::JSON_XS](https://metacpan.org/pod/Mojo::JSON_XS)
```
❯ wrk -H 'Cookie: REDACTED' --duration 60 --latency -T 20 https://conch.joyent.us/workspace/496f76b4-8245-4d41-8d97-42fe988401c5/device
Running 1m test @ https://conch.joyent.us/workspace/496f76b4-8245-4d41-8d97-42fe988401c5/device
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     4.96s   892.73ms   8.29s    76.52%
    Req/Sec     2.08      3.08    19.00     90.48%
  Latency Distribution
     50%    4.76s
     75%    5.28s
     90%    6.28s
     99%    7.93s
  115 requests in 1.00m, 141.28MB read
Requests/sec:      1.92
Transfer/sec:      2.35MB
```
😞

**Comment by lseppala** [comment]
I deployed rendering JSON with `Cpanel::JSON::XS` via [Mojo::JSON_XS](https://metacpan.org/pod/Mojo::JSON_XS) and collected some results

Before Cpanel::JSON::XS: (best of three identical runs)

```
❯ wrk -H 'Cookie: R' --latency -T 20 --duration 60 -c 2 -t 2 https://staging.conch.joyent.us/workspace/496f76b4-8245-4d41-8d97-42fe988401c5/device
Running 1m test @ https://staging.conch.joyent.us/workspace/496f76b4-8245-4d41-8d97-42fe988401c5/device
  2 threads and 2 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     3.88s   430.44ms   4.96s    66.67%
    Req/Sec     0.00      0.00     0.00    100.00%
  Latency Distribution
     50%    3.90s
     75%    4.10s
     90%    4.56s
     99%    4.96s
  30 requests in 1.00m, 28.35MB read
Requests/sec:      0.50
Transfer/sec:    483.16KB
```

After Cpanel::JSON::XS: 

```
❯ wrk -H 'Cookie: R' --latency -T 20 --duration 60 -c 2 -t 2 https://staging.conch.joyent.us/workspace/496f76b4-8245-4d41-8d97-42fe988401c5/device
Running 1m test @ https://staging.conch.joyent.us/workspace/496f76b4-8245-4d41-8d97-42fe988401c5/device
  2 threads and 2 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     3.60s   290.89ms   4.26s    68.75%
    Req/Sec     0.00      0.00     0.00    100.00%
  Latency Distribution
     50%    3.57s
     75%    3.82s
     90%    3.93s
     99%    4.26s
  32 requests in 1.00m, 30.24MB read
Requests/sec:      0.53
Transfer/sec:    515.74KB
```

As you can see, there's some improvement, but not a huge amount. Dancer was responding in 1.64s in the 90th percentile.

**INTERESTINGLY** I was using 2 threads with 2 connections, because the default of 2 threads with 10 connections caused most requests to time out. This occurred both pre- and post- JSON::XS. The `wrk` results look like:

```
❯ wrk -H 'Cookie: R' --latency -T 20 --duration 60 https://staging.conch.joyent.us/workspace/496f76b4-8245-4d41-8d97-42fe988401c5/device
Running 1m test @ https://staging.conch.joyent.us/workspace/496f76b4-8245-4d41-8d97-42fe988401c5/device
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    19.40s   332.81ms  19.93s    62.50%
    Req/Sec     3.24      4.05    10.00     70.59%
  Latency Distribution
     50%   19.39s
     75%   19.72s
     90%   19.93s
     99%   19.93s
  17 requests in 1.00m, 16.27MB read
  Socket errors: connect 0, read 1, write 0, timeout 9
Requests/sec:      0.28
Transfer/sec:    277.21KB
```

I found the same thing happening when I by-passed the nginx proxy and connected directly to hypnotoad.

 I am not sure why this is happening. It does not occur when testing production.

**Comment by lseppala** [comment]
Another variable I remembered:

* The Dancer2 instance is running on a Debian VM. Mojo is running on SmartOS.

Fingers crossed that's not the issue...

**Comment by lseppala** [comment]
I discovered that `DateTime::Format::Pg->parse_timestamptz` in `Conch::Time` is contributing significantly to the slow performance. I will replace it with a simpler method.

**Comment by lseppala** [comment]
The reason I used `DateTime::Format::Pg` was to format Postgres-formated timestamps into [RFC 3339](https://tools.ietf.org/html/rfc3339) timestamps.

For example: `2018-01-12 15:42:44.927059-07` becomes `2018-01-12T22:42:44.927Z

I replaced `DateTime::Format::Pg` with `DateTime::Format::Strptime` in hopes it would be more performant. It still constructs a `DateTime` object like `::Format::Pg`, but it uses a single specified strptime parser.

It was still slower by nearly a magnitude over not performing any formatting when testing locally. It was roughly the same performance as `::Format::Pg`, if not slightly slower.

It seems that the root culprit is the `DateTime` object created by both of these libraries, [which has known performance issues at scale](https://www.nntp.perl.org/group/perl.datetime/2012/05/msg7831.html).

The `DateTime` objects provide more functionality than we need. Rather than using `DateTime` for formatting, I propose to simply transform the PG timestamps to RFC 3339 timestamps _and preserving the timestamps_.  `2018-01-12 15:42:44.927059-07` will become `2018-01-12T15:42:44.927059-07:00`. Simply preserving the timestamps allow us to avoid doing timezone math (e.g. what is +07 in UTC on Feb 28 at 15:00?) that would necessitate bringing in a library. For the simple case of `+00:00` (already UTC), we can replace it with `Z`.

I haven't tried any of the alternatives mentioned in various mailing list threads, and I am admittedly unaware of other solutions. Please inform me if you have any experience with this issue or know of other solutions.

**Comment by lseppala** [comment]
Tested now: just creating `DateTime`s with `DateTime->now` for every `Conch::Time->new` is 3-5 times slower.

**Comment by sungo** [comment]
Are actually using any DateTime features in the codebase right now or are we always just creating new Conch::Time objects so we can get `to_string()`? If we aren't doing any datetime work, Conch::Time could string parse the timestamp itself without needing any DateTime modules.

**Comment by sungo** [comment]
And maybe a to_datetime method just in case we ever need one
