### ISSUE TITLE
Permisions, as defined on the user_workspace_role table, should cascade to sub-workspaces unless overriden on the workspace

### ISSUE THREAD

**Issue by bdha** [joyent/conch#373]

**Comment by karenetheridge** [comment]
more info at https://app.liquidplanner.com/space/174715/projects/show/47016855

**Comment by karenetheridge** [comment]
Possibly affected endpoints -- we need to figure out if and how these should change:

* `GET /user/:user_id` - returns all workspaces+roles for this uesr. should we add parent workspaces, and for each workspace row include the maximum permission that us
er has for the entire tree?
* `GET /user`        - as in `GET /user/:user_id` but for all users.
* `GET /workspace/:workspace_id` - gets permissions for this user for the current workspace.  should we instead show the maximum permission on all parent workspaces to this one?
* `GET /workspace` - as in `GET /workspace/:workspace_id` but for all workspaces.
* `GET /workspace/:workspace_id/child` - as in `GET /workspace/:workspace_id` but for all workspaces beneath this one.
* `GET /workspace/:workspace_id/user` - as in `GET /workspace/:workspace_id` but lists all users and permissions for this workspace.

All the other endpoints that do permission checks are straightforward - e.g. when checking if a user has permission to access a device,
instead of checking the permissions for just the workspace(s) that device is in, we will also check permission for all ancestors of that workspace(s).

**Comment by karenetheridge** [comment]
More reqs:

* permissions for a workspace can only be set by someone with admin perms on that workspace (this should already be the case - check)
* when requesting to add permissions:
** return 400 if that user already has a higher permission on this workspace or a parent
** return 204 if that user already has the same permission on this workspace or a parent
** return 201 if we actually created a new `user_workspace_role` record

**Comment by sungo** [comment]
- we need #443 to resolve the issue of GLOBAL being special.

- for general permissions checks, the user should effectively have the `max()` permissions in the relevant tree.

- As noted above, if an admin attempts to give a user lower permission than they have inherited, the admin should receive an error. 

- whenever we list a user and their permissions, we should include the effective permission, and the workspaces they have access to because of it. So if a user is 'rw' on a workspace, the list should return that workspace and all the subworkspaces with the permissions listed as 'rw' 

- We probably need a flag the user specific endpoints or a new endpoint to allow an admin to see the explicit permissions and understand *why* a user as the access they do.

**Comment by karenetheridge** [comment]
As part of the migration I will remove all redundant user_workspace_role entries for global admins only; the remainder are to be cleaned up with the `clean_permissions` script.  The first set of redundant rows can be viewed via:

```
select user_account.email, workspace_id, role, workspace.name from user_workspace_role
  join user_account on user_account.id = user_workspace_role.user_id 
  join workspace on workspace.id = user_workspace_role.workspace_id
  where user_id in (
        select user_account.id from user_account
        join user_workspace_role on user_account.id = user_workspace_role.user_id
        join workspace on user_workspace_role.workspace_id = workspace.id
        where workspace.name = 'GLOBAL' and user_workspace_role.role = 'admin' )
and workspace.name != 'GLOBAL';
```

(or see my private gist)

**Comment by karenetheridge** [comment]
We also need a way to set the `is_admin` flag for a user, since inviting them to the GLOBAL workspace won't do the same thing. (and we shouldn't be creating users through the workspace-invite interface anyway - see #452.)
