### ISSUE TITLE
Raise flag on unparseable reports

### ISSUE THREAD

**Issue by bdha** [joyent/conch#377]
If a host is submitting reports we can't parse, we want to flip a bit somewhere and display that in the UI.

This helps with diagnosing service problems.

A device setting would work for this.

**Comment by karenetheridge** [comment]
I would suggest a flag on device_relay_connection, which will help us figure out what DRD is being naughty at the same time.

**Comment by karenetheridge** [comment]
We also need to figure out the mechanism by which the flag is cleared. Leaving "bad report" flags lingering forever in the db is shouting wolf.

**Comment by sungo** [comment]
When we post up device reports, we have a few places where bad data could cause explosions:

* The initial JSON Schema based data validation
* When the validations run. Bata data will likely cause an exception, aka ERROR state
* When we use the report data to populate the device tables

We log the JSON Schema failures but I don't think we store the bad device report. The failure data certainly isn't queryable.

The validations error we sort of catch now. Validation states aren't currently directly tied to the device report ID but that's on the list to fix soon. That's a situation that the UI should be exposing loudly if it's not already.

We have no method of marking the third.

**Comment by sungo** [comment]
I think I'd like to put the 'bad' flag on the device report table itself.  We'd change the methodology to always store the DeviceReport, even if it fails JSON Schema validation. Then if it caused any of the three states in my previous comment, we flag the report row itself as 'bad'.

This would give us a permanent record of bad reports and not require a state that must be cleared later. If the latest report for a device is marked bad, we can flag it in the UI and CLI

**Comment by karenetheridge** [comment]
if we have any sort of monitoring on the relays, it would be great if we can send up a flag saying "relay X in location Y is sending bad reports", but that requires support on the other end. something to think about.

**Comment by karenetheridge** [comment]
needs discussion/spec. What should we do when we receive a bad report? right now we just reject it with a HTTP 400 response and log it. this is not very visible.

**Comment by karenetheridge** [comment]
> We log the JSON Schema failures but I don't think we store the bad device report. The failure data certainly isn't queryable.

We can store the bad report *if* it's valid json, but otherwise we can't.  (Actually I suppose we could.. we'd just embed it as a string into a new json object, a lá: `{"invalid_json" : "\{encoded sorta json here... \}"}`.

I would propose the following:

- add an 'invalid' boolean column to the `device_report` table, indicating that the report did not pass the DeviceReport json schema
- add an 'invalid_report' boolean column to the `device` table itself (and return it in the endpoints that use the `DetailedDevice` json schema - see https://github.com/joyent/conch/blob/master/json-schema/response.yaml) indicating that the most recent report received could not be parsed
- update the device report submission endpoint to store the bad report if it could not be parsed, and to set the two flags above.
- possibly also set the two flags if the validations returned an 'ERROR' (as opposed to 'FAIL') condition?

Then, the ui just needs to flash a big red light when it sees the 'invalid_report' flag set on a device.

**Comment by karenetheridge** [comment]
question: should `device.health` be set to 'ERROR' upon receipt of a bad device report?

Observation: between the `device.health` field and the new `device_report.invalid` flag, `device.validated` is quite redundant and we should remove it along with the endpoint that sets it (`POST /device/:id/validated`).
