### ISSUE TITLE
Add dupe MAC detection

### ISSUE THREAD

**Issue by bdha** [joyent/conch#382]
To the network validations. Look for other MACs that match this MAC. Raise a flag.

Subtleties: if a card is moved from one host to another, and the other host doesn't mark that NIC as deactivated, the validation may fail.

**Comment by perigrin** [comment]
This is just a validation, not part of a DCIM subsystem (though it would query one).

Also note, I think we want the failure in that case so we know to update the old host that the NIC is gone.

**Comment by karenetheridge** [comment]
Validations will never detect this situation because the conflict already gets resolved before they run. `mac` is the primary key of the `device_nic` table -- only one row can have that mac at any given time. When updating the database with data from a new report, we deactivate all existing device_nic entries with the macs in the report, and move those rows to the current device.

If we instead want to fail loudly, e.g. "this mac is already in use by device <serial>; submit a new report from that device first removing that mac before you can submit a report for the new device", we can do that (with exact behaviour TBD - at present we always accept a report), but that's not in the scope of validations.

**Comment by perigrin** [comment]
So based on ether's comments above. I'm closing this because the current version of conch cannot cleanly address this problem and we plan on addressing this style of problem entirely differently in future versions.
