### ISSUE TITLE
Replace version.json with API call

### ISSUE THREAD

**Issue by bdha** [joyent/conch#384]
Agents query a flatfile (version.json) to get the version of software they should be running. Right now this data is stored on the webserver. This is fragile and we lose useful debugging information.

Need to store versions for each product in the database, with a non-default "environment."

Something like:

product, user, environment, version, created, updated, deactivated

We want to be able to track when versions are updated.

The user field is somewhat critical -- the file(s) we push for Joyent will be different from Samsung will be different from $random customer, etc.

Environment = production, staging, dev, etc.

GET query would be something like one of the following?

/product/:product/:environment/version
/product/:product/version?environment=:environment
/product/:environment

And a POST would follow similar structure to GET, but update the version, log the change, etc.

Only admins should be able to POST.

**Comment by sungo** [comment]
paging @jemershaw

**Comment by jemershaw** [comment]
I am unclear as to what the user setting would be used for, but maybe this could be set in some user profile setting. I am not sure how helpful the environment setting would be since environment would just be a different url.

| Endpoint | Description |
|--|-- | 
| /product/:product/version | could be used for the default setting/current version |
| /product/:product/version/:version_number | specific version # |
| /product/:product/version?prev_release=1 | Get previous releases # |
| /users/me/product/:product/version | User specific endpoint |

For the previous releases it is only helpful if we aren't using semver for the agents.

I need to think about this a little more, but maybe @daleghent has some insight on how we could use this endpoint.

**Comment by jemershaw** [comment]
I'd say for now lets close this ticket and I'll work with @daleghent to gather requirements.

**Comment by daleghent** [comment]
Not sure we need to close the ticket - this can be a good place to record our thoughts on the subject. I like your proposed format as a theme to work off of. I'll give this some deeper thought, myself.
