### ISSUE TITLE
Add endpoint which will allow hardware_product_profile insert/update from api

### ISSUE THREAD

**Issue by bdelano** [joyent/conch#511]
At the moment this is blocking me from adding any legacy device as quite a few servers and network switches/appliances will need their own profiles

**Comment by karenetheridge** [comment]
how about: `POST /hardware_vendor/:hardware_vendor_name/profile` which takes the following json payload:

```
    {
        name => ..., # (required)
        alias => ..., # (required)
        specification => ..., # optional, json blob that is stored as-is
        sku => ..., # optional
        generation_name => ..., # optional
        legacy_product_name => ..., # optional
    }
```

**Comment by karenetheridge** [comment]
IMO the schemas here are wrong -- right now, a `hardware_product_profile` can only refer to one `hardware_product`.  Instead, multiple `hardware_product`s should be able to use the same profile.  Therefore, instead of relating the two with `hardware_product_profile.hardware_product_id`, there should instead be a `hardware_product.hardware_profile_id`.

This would allow us to create a new profile when creating a product, *or* referencing an existing profile id and creating the product using that.

**Comment by bdelano** [comment]
Although I can't think of a situation where the profile would be reused, I agree that the current setup is the reverse of what you would expect. 

I would need to understand better what components of the API actually use the hardware profile table, but to me it would make more sense for this to be a set of key value pairs tied to a hardware product ID.  This way we would only have the specific information for that devices profile as there are a few fields that do not apply to network devices.  

Also, I fully understand that a change like this may completely break the workflow so certainly not a 'must change'.

**Comment by sungo** [comment]
To provide some history and context here, the `hardware_product` table has a new-ish jsonb `specification` field. This arose from a time I recommended collapsing the `hardware_product` and `hardware_product_profile` tables together because they are 1:1. The `specification` jsonb was intended to follow some as-yet-undefined standard that would replace the profile table entirely, something with a schema we could validate against. The biggest issue with the profile table is that it is completely inflexible and designed around the notion that we only have servers and storage servers at that. It doesn't work for network devices and it doesn't work really well for compute.

To date, two hardware products have been converted to some early design that bdha had but, to my knowledge, never documented. Further, [Conch Locker](https://github.com/joyent/conch-locker) is designed to replace all of this with a system that can, in theory, handle any hardware we want to describe.

For right now, in my opinion, we should keep on with the current world, adding endpoints that simply CRUD the existing tables, as suboptimal as they are, until we can get a better sense of the time line on Locker. If that timeline looks to be too far out, I recommend we start movement towards defining a schema for the `specification` column on `hardware_product` and transitioning to that.

**Comment by sungo** [comment]
As far as key/value pairs are concerned, we have a tendency to start advocating for key/value pairs whenever it seems like it might be difficult to define a schema or specification for the data. We've had a similar discussion in the last 6 months about pretty much every concept in the database.

We're using a relational database. We need to figure out how these concepts relate to each other and how to describe them and record that relationship, as one does, in the sql schema. Key/value pairs are attractive because they let folks YOLO in any data they want but they make detailed queries extremely painful and they end up with every entry being described in some different way because we can't enforce a schema.

If what we want is a database that lets us describe every entry completely differently without worrying about schemas, then we should move to a database designed for that sort of work, some sort of noSQL thing like MongoDB. 

To be clear, I don't think that's a good idea in the slightest and we will hate the result. But we either need to take the time to describe our data properly or move to a system that lets us not bother.

**Comment by karenetheridge** [comment]
@bdelano, do you need to add (or change?) profile data for an existing hardware_product, or add a new hardware_product + hardware_product_profile pair? This will help determine what backend changes I need to make. (and we'll probably need to ninja your db changes in manually anyway if you need them "soon", because of the release schedule.)

**Comment by bdelano** [comment]
@karenetheridge I should just need to add new product/profile but assuming i will make a few mistakes having the ability to update these would probably be the ideal situation.

**Comment by karenetheridge** [comment]
@belano ok, I will modify the 'create a new hardware product' endpoint to include profile information.
