### ISSUE TITLE
`/device?key=value` can only return a single device

### ISSUE THREAD

**Issue by sungo** [joyent/conch#583]
In #449, the `/device` endpoint was extended to support key/value pair searching, specifically against the device settings. As currently implemented, the user can only get a single device back using this function. The problematic code seems to start at https://github.com/joyent/conch/blob/master/lib/Conch/Controller/Device.pm#L184 . The assumption seems to be that device settings are unique but they are not so in the database schema or practical usage.

In the shell, at least, the main use case for a function like this is to stay "give me all devices where the setting `joyent.purpose` is `MANTA`".

**Comment by karenetheridge** [comment]
I'm not sure what to do here without affecting the existing search-for-a-single-device endpoint... it doesn't seem right to return either a hashref or an arrayref depending on what type of thing you're searching for...

**Comment by sungo** [comment]
Perhaps a new endpoint like `GET /device/search`?

**Comment by perigrin** [comment]
it's not really depending on what type of thing you're searching for but on the kinds of results you get. IN theory of `hostname`, or `ipaddr` wasn't unique in the database then we'd still have this issue.

So my current suggestion is to just always return an ArrayRef. I think the shell is the only client we have consuming that endpoint currently and we can just fix it.

In a perfect universe we'd have clients provide an Accept Header on the request so that we could determine if they could handle legacy clients by returning a HashRef for them but an ArrayRef for newer clients (or both if clients can accept either).
