### ISSUE TITLE
Accept metrics from device reports in a new section

### ISSUE THREAD

**Issue by sungo** [joyent/conch#624]
In #458, I proposed a new API endpoint to accept metrics from the edge, pivoting those into an external store. In the months since, it's become clear to me that this sort of change in livesys and the relay is probably unreasonable. A more simple approach would be to accept metrics in the device report itself and expose those in the stats endpoint proposed in #623. This would allow the metrics to be used in validating a device and also allow them to be polled for long term storage in a more appropriate system.

I will propose this over the in the livesys repo as well but I propose the following format at the root of the device report.

```
{
  metrics: [
    {
      timestamp: 1548360053,
      name: "temp.cpu0",
      value: 67.5,
    },
    {
      timestamp: 1548360053,
      name: "temp.cpu1",
      value: 54.3,
    },
  ],
}
```

This requires #623. This supersedes and closes #458.  This will supersede and close joyent/conch-relay#152, with a new ticket linking in from that repo shortly.

**Comment by daleghent** [comment]
Since this will disembody component-specific metrics from the components, what method do you envision for programmatically tying the two back together? If I'm validating a drive (or other such discrete component) and I need to check whether its temperature is out of bounds, how should I reliable tie it and its temperature metric together without undue backbends around parsing KV values?

Right now if I want to know the temperature of the disk with serial number ABCDE123, I simply look up `$report->{disks}{ABCDE123}{temp}`. How can we make the proposed separation similarly frictionless?

**Comment by karenetheridge** [comment]
@daleghent I don't see a problem in looking for the key 'disk.ABCDE123.temp' in the metric section of the report.

**Comment by daleghent** [comment]
I understand that, however it just seems to me that looping over the contents of an N-member array every time I want to look for a specific metric is a step backwards from being able to just reference the metric directly. Obviously we can make a function that'll rummage through the haystack for us if we're looking for `disk.ABCDE123.temp` (something like a `getmetricbyname()` but it just feels not as performant? I honestly don't know how much array member iteration costs so perhaps I'm worried about nothing, but I would advocate for such lookup functions to be a part of this move. These utility lookup functions can then be consumed and used by validation code.

**Comment by sungo** [comment]
@daleghent I want metrics in a dedicated section so we can track and handle them separately. My proposed format is clearly not something you like. Can you please provide an example of what you'd like?

**Comment by karenetheridge** [comment]
@daleghent who is "we" here? when would we need to look for a specific disk temperature other than in the validation itself?

**Comment by daleghent** [comment]
The question I'm raising is around how we access the metric data. Why we're splitting it off into its own branch is obvious and good and totally should be done. But we still need to use this data and be able to look it up and use it under specific contexts, and I think it would be good to ensure that the new structure we insert metric data into _facilitates_ an ease of use and performance that is at least close to what we currently enjoy.

Right now we enjoy a direct shot to the data - the report JSON is deserialized to a hash and we just reference the metric or other data we want by constructing an appropriate reference. Ie, if I want to know what the temperature of disk ABCDE123 is, I look up `$report->{disks}{ABCDE123}{temp}`. Simple. Straight-forward. Obviously this has drawbacks such as if the report format changes.

How will that change under the proposed scheme? If we now need, say, accessor methods to do the above for us, that is fine with me... I just want to be clear on whether that's considered to be a part of this change or not. And if we do need to create accessor methods to facilitate the lookup of metrics for a given thingy (CPU, disk, whatever), will this proposed data structure be appropriate for that and not get in the way? I just want to be sure that we don't have to do anything torturous or potentially unperformant to reassociate a metric with its component or vice versa.

**Comment by karenetheridge** [comment]
> The question I'm raising is around how we access the metric data. Why we're splitting it off into its own branch is obvious and good and totally should be done. But we still need to use this data and be able to look it up and use it under specific contexts

Again, who is "we" here? And what contexts?

> I just want to be sure that we don't have to do anything torturous or potentially unperformant

Surely that's up to the implementor to figure out, and to push back if it's a problem. It seems to me you're fishing for issues that don't exist?

**Comment by daleghent** [comment]
> Again, who is "we" here? And what contexts?

"We" is us or anyone who needs to use the metric data. Who "we" are is immaterial to this, so I'm curious why it matters to you. In technical discourse, I tend to use "we" instead of "I" because it's not just me who has an interest or involvement in this change.

> Surely that's up to the implementor to figure out, and to push back if it's a problem. It seems to me you're fishing for issues that don't exist?

Is it not appropriate to try to map the whole idea out before it's implemented? I want to understand how the data in its new form will be accessed and used. I would argue that this is a pretty important part of understanding the proposed change.

**Comment by sungo** [comment]
The "we" matters because features need to be written to handle the use cases of the customer. So identifying the customer is very important.

At this time, the customer of the metrics information, as far as I'm aware, is the validation system. Since the validation system is operating against a single report at a time, I don't see an issue in my original format. Mapping on an array is a trivial operation.

@daleghent, you seem to have other customers or consumers in mind. Can you please detail those?

**Comment by daleghent** [comment]
OK, just to placate you, I'll define "we" as me. I was attempting to be inclusive by using "we" but that appears to be mystifyingly distracting from the technical conversation that I'm trying very hard to keep on track here. There are no hidden customers, there are no hidden interests.

How and how well we access and associate data in the report is important to me because a large part of that hinges on the format of the report itself. If the format of the report is made such that accessing any of the data in it becomes unreasonably arduous or we are forced to make deflating compromises, that's a problem. It's a problem because to fix it we need to go back and change agents, of which there are multiple. It means report formats change. It's extra work that can be avoided if the design of the data's structure _and how it is used_ is thought-out and deliberated on.

I'm not raising any particular flags with your proposal other than asking how we would look up things in practice (which is why I raised the examples of lookup functions/accessor methods.) We _will_ need to do this kind of stuff, so I'd like to ensure that the data's structure facilitates working with it and won't demand tweaks or redesigns to accommodate. Haystacks of data, as arrays usually are, get my attention because I know how they can get unruly and cause performance problems. If you say array mapping is trivial and the way we're using data here is alright, then that's good for me and that's really the only discussion I was looking for.

**Comment by sungo** [comment]
So. I can't actually lock this conversation since everyone has write access. So what I'm going to do instead is close the ticket out and everyone can hash it out in chat instead of a public ticket.

**Comment by karenetheridge** [comment]
Since appears to be of great concern, here is the full diff of lib/Conch/Validation/DiskTemperature.pm, assuming a format change from

```
{
  disks => {
      DEADBEEF => {
         temp => 20,
         ...
      },
      COFFEE => {
         temp => 65,
         ...
      },
  },
}
```

to:

```
{
  metrics => [
     {
       name => 'temp.disk.DEADBEEF',
       value => 20,
     },
     {
       name => 'temp.disk.COFFEE',
       value => 65,
     },
  ],
  disks => {
      DEADBEEF => { ... },
      COFFEE => { ... },
  },
}
```

```
diff --git a/lib/Conch/Validation/DiskTemperature.pm b/lib/Conch/Validation/DiskTemperature.pm
index eda425e1..e4e919ae 100644
--- a/lib/Conch/Validation/DiskTemperature.pm
+++ b/lib/Conch/Validation/DiskTemperature.pm
@@ -10,6 +10,8 @@ has 'description' => q(
 Validate the reported disk temperatures are under the maximum threshold
 );
 
+use List::Util 'first';
+
 sub validate {
        my ( $self, $data ) = @_;
 
@@ -22,8 +24,9 @@ sub validate {
        while ( my ( $disk_sn, $disk ) = ( each $data->{disks}->%* ) ) {
                next if !$disk->{transport} || fc( $disk->{transport} ) eq fc('usb');
 
+               my $metric = first { $_->{name} eq 'temp.disk.'.$disk_sn } $data->{metrics}->@*;
                $self->fail("No temperature reported for disk $disk_sn") && next
-                       unless defined( $disk->{temp} );
+                       unless $metric;
 
                # from legacy validation
                my $MAX_TEMP = 51;
@@ -31,7 +34,7 @@ sub validate {
 
                $self->register_result(
                        expected     => $MAX_TEMP,
-                       got          => $disk->{temp},
+                       got          => $metric->{value},
                        cmp          => '<',
                        component_id => $disk_sn,
                );
```
