### ISSUE TITLE
Access all the things using their unique identifiers

### ISSUE THREAD

**Issue by sungo** [joyent/conch#799]
In v3, I need to be able to access entities using any unique identifier. 

For instance, a 'workspace' has a uuid and a name. When using the `/workspace/:identifier` routes, I need to be able to use both the workspace's uuid and its name, like `/workspace/:uuid` and `/workspace/:name`.

As far as use cases are concerned, most of the time, users of the shell will not have the uuid for an entity. They want to look up a workspace by its name or a device by its serial number or a hardware product by its name. If the API only accepts UUIDs in its routes, every time a user asks for an entity, the shell has to get all of them and manually dig through them. Since the fields are already unique identifiers on the table in question, the database has indexes, and it is faster, and more customer-friendly, to do those searches in the API/database.

**Comment by karenetheridge** [comment]
This is not as straightforward as it seems because not every entity has a unique and not-null name.

* `/workspace/` endpoints already support querying by id or name.
* `/device` - in v3 we will have both id and serial_number. ok.
* `/dc` - only vendor is not-null. vendor_name is not. There is no 'name' column. Should there be one?
* `/rack_role` - already supports queries by name.
* `/rack` - there is a `name`. ok.
* `/relay` - in v3 we will have both id and serial_number. ok.
* `/user` - we already support either id or email in most places.
* `/hardware_product` - a plethora of text fields abound here. these should be cleaned up.
* `/room` - as /hardware_product: lots of names.
* `/validation` - already supports queries by name.
* `/validation_plan` - already supports queries by name.
* `/validation_state` - these have no name.
* `/hardware_vendor` - already supports queries by name.
* `/layout` - these have no name.

**Comment by sungo** [comment]
The 'name' field was just an example. Like the first line says: `I need to be able to access entities using any unique identifier.` If the entity has unique identifiers called 'name', 'location', 'flavor', 'mac_address', I want to be able to look up that entity using all those fields.

On the flip side, if the entity's unique identifier is solely a UUID, then I can only access that item using the UUID so no other lookups are required.

I am not asking for extra unique identifiers to be added. I am asking to be able to access entities using the non-uuid unqie identifiers they already have.

**Comment by karenetheridge** [comment]
Please update this ticket with any specific endpoints that have been identified to be missing and would be useful, so they can be implemented more quickly. An exhaustive search through all the endpoints to search for every possible combination of possible unique inputs is unlikely to happen in the immediate future, and some combinations are likely to require less trivial database queries.

**Comment by sungo** [comment]
Neither of us have time to do an exhaustive search right now. Take this as a request to add these lookups while you're dealing with some entity. Eventually they'll all be taken care of.

**Comment by karenetheridge** [comment]
Basically everything is covered now except rack, and racks don't presently have a globally unique column (rack.name can be reused in another room).
